# Site settings
title: Блог
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Блог обо всём на свете. 
  
  Меня зовут Тимур. Я веб и мобильный разработчик, писатель и эстет.
baseurl: "/rublog"
url: "http://famer.github.io/"

# Build settings
markdown: kramdown
